### ISSUE TITLE
Lua error when leveling up i cataclysm classic

### ISSUE THREAD

**Issue by Sundur94** [mBlinkii/mMediaTag#103]
1x ...UI_mMediaTag/modules/nameplates/healthandexecute.lua:188: attempt to call global 'GetSpecialization' (a nil value)
[string "@ElvUI_mMediaTag/modules/nameplates/healthandexecute.lua"]:188: in function `updateAutoRange'
[string "@ElvUI_mMediaTag/init.lua"]:359: in function `?'
[string "@!mMT_MediaPack/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ack/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@!mMT_MediaPack/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ack/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@!mMT_MediaPack/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'

I get the error whenever i level up.

I am using version:
3.40
Release 05.06.2024

And Elvui:
13.66

**Comment by mBlinkii** [comment]
Hi, thx for your feedback. this is fixed in the dev version of mMT, https://github.com/mBlinkii/mMediaTag/compare/6e2d63e9ab82...ae5aca20c461.

**Comment by mBlinkii** [comment]
I have to correct myself, the error has already been fixed in version 3.40 and should no longer occur.

**Comment by mBlinkii** [comment]
so please make sure that you are really on the current version 3.40. If the error persists, please try to reinstall mMT, if you do it manually, please delete the old folders beforehand.

**Comment by mBlinkii** [comment]
If the error is still there, please show a screenshot of the /estatus here.

**Comment by Sundur94** [comment]
I used the reinstall function through curseforge, and the error no longer appears whe ni level up. Thanks!
