### ISSUE TITLE
Get error while fighting in delve

### ISSUE THREAD

**Issue by billyb3** [mBlinkii/mMediaTag#146]
`1146x ...dOns/ElvUI_mMediaTag/modules/unitframes/portrait.lua:210: attempt to index field '?' (a nil value)
[string "@ElvUI_mMediaTag/modules/unitframes/portrait.lua"]:210: in function <...dOns/ElvUI_mMediaTag/modules/unitframes/portrait.lua:204>
[string "@ElvUI_mMediaTag/modules/unitframes/portrait.lua"]:247: in function <...dOns/ElvUI_mMediaTag/modules/unitframes/portrait.lua:239>
[string "@ElvUI_mMediaTag/modules/unitframes/portrait.lua"]:632: in function <...dOns/ElvUI_mMediaTag/modules/unitframes/portrait.lua:621>
[string "@ElvUI_mMediaTag/modules/unitframes/portrait.lua"]:658: in function <...dOns/ElvUI_mMediaTag/modules/unitframes/portrait.lua:638>
[string "@ElvUI_mMediaTag/modules/unitframes/portrait.lua"]:755: in function <...dOns/ElvUI_mMediaTag/modules/unitframes/portrait.lua:750>

Locals:
portraitFrame = mMT_Portrait_Target {
 shadow = mMT_shadow-Target {
 }
 portrait = mMT_portrait-Target {
 }
 PixelSnapDisabled = true
 mask = MaskTexture {
 }
 allEvents = <table> {
 }
 unit = "target"
 extraBorder = mMT_extraBorder-Target {
 }
 settings = <table> {
 }
 iconbg = mMT_iconbg-Target {
 }
 isBuild = true
 isDesaturated = false
 scriptsSet = true
 texture = mMT_texture-Target {
 }
 textures = <table> {
 }
 extra = mMT_extra-Target {
 }
 name = "Target"
 cornerBorder = mMT_cornerBorder-Target {
 }
 corner = mMT_corner-Target {
 }
 events = <table> {
 }
 border = mMT_border-Target {
 }
 extraShadow = mMT_extraShadow-Target {
 }
 innerShadow = mMT_innerShadow-Target {
 }
 unit_is_dead = false
 parent = ElvUF_Target {
 }
}
classification = "rareelite"
extraTextures = nil
(*temporary) = nil
(*temporary) = mMT_extra-Target {
 PixelSnapDisabled = true
}
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
E = <table> {
 mylevel = 80
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 myspecRole = "DAMAGER"
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ClearTexture = 0
 Tooltip = <table> {
 }
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = false
 myrole = "DAMAGER"
 UFParent = ElvUFParent {
 }
 InfoColor2 = "|cff9b9b9b"
 myname = "Teleria"
 ActionBars = <table> {
 }
 DebugTools = <table> {
 }
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 ClassicAnnivHC = false
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 3
 UnlocalizedClasses = <table> {
 }
 callbacks = <table> {
 }
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 5120
 versionString = "13.81"
 DataBars = <table> {
 }
 InfoColor = "|cff1784d1"
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Horde"
 myrace = "BloodElf"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Blood Elf"
 myclass = "HUNTER"
 wowdate = "Nov 19 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "Akama"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 LibsMinor = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.711111
 resolution = "5120x1440"
 TBC = false
 AnimElastic = <table> {
 }
 QualityColors = <table> {
 }
 media = <table> {
 }
 data = <table> {
 }
 Options = <table> {
 }
 ClassicHC = false
 HiddenFrame = Frame {
 }
 Media = <table> {
 }
 name = "ElvUI"
 TimeFormats = <table> {
 }
 ShortPrefixStyles = <table> {
 }
 versionDev = false
 Blizzard = <table> {
 }
 wowbuild = 57689
 RegisteredInitialModules = <table> {
 }
 TotemTracker = <table> {
 }
 RegisteredCooldowns = <table> {
 }
 SpecInfoBySpecID = <table> {
 }
 ObjectEventTable = <table> {
 }
 title = "|cff1784d1ElvUI|r"
 EditorMode = <table> {
 }
 MapInfo = <table> {
 }
 frames = <table> {
 }
 physicalHeight = 1440
 NewSignNoWhatsNew = "|TInterface\OptionsFrame\UI-OptionsFrame-NewFeatureIcon:14:14:0:0|t"
 ClassicSOD = false
 Retail = true
 MountIDs = <table> {
 }
 AnimShake = <table> {
 }
 DisabledMovers = <table> {
 }
 mult = 0.750000
 UserList = <table> {
 }
 MediaUpdated = true
 TagInfo = <table> {
 }
 myspecName = "Beast Mastery"
 PixelMode = true
 serverID = 84
 PrivateAuras = <table> {
 }
 myspecIcon = 461112
 myspec = 1
 initialized = true
 ultrawide = 2560
 GetFormattedTextStyles = <table> {
 }
 charSettings = <table> {
 }
 FrameLocks = <table> {
 }
 myguid = "Player-84-05B150A4"
 loadedtime = 1473545.281000
 ConfigTooltip = ElvUI_ConfigTooltip {
 }
 SpecInfoBySpecClass = <table> {
 }
 Spacing = 0
 Border = 1
 statusBars = <table> {
 }
 EasyMenu = ElvUI_EasyMenu {
 }
 SpellBookTooltip = ElvUI_SpellBookTooltip {
 }
 private = <t`

**Comment by mBlinkii** [comment]
Thank you for reporting this, I have fixed it. https://github.com/mBlinkii/mMediaTag/commit/4d2dceef41d3f544db13ac89363f1fc8793c4e03

**Comment by billyb3** [comment]
Thank you for the quick response and fix!
