### ISSUE TITLE
Splash screen visible at all time

### ISSUE THREAD

**Issue by djodars89** [mBlinkii/mMediaTag#32]
![image](https://user-images.githubusercontent.com/30188668/197914849-65cc5d99-7e75-4fa6-a298-c3a15993df79.png)

First time I install this but this is right after 10.0 release so unsure if it was an issue before.

This windows / splash screen / image is on top of the game at all times and cannot be closed.

**Comment by fortitudomultis** [comment]
Can confirm, seeing the same thing. Have to disable mMediaTag until this is fixed.

**Comment by DarthVapers** [comment]
Checked the updates on Curse and TukUI apps - both say updated today (10 hours ago as of writing) however the version # is still incorrect and the volume is still set to display.. 

in core/mSettings.lua: 
line 339 change to: ["VolumeDisplay"] = {["enable"] = false},

in ElvUI_mMediaTag.toc
line 1 change to:  ## Interface: 10000
line 4 change to:  ## Version: 2.88.3

Started up and no errors or issues. This is a temp fix until proper fix and update pushes thru available channels.
