### ISSUE TITLE
Having Tooltip Enabled makes spell names disappear.

### ISSUE THREAD

**Issue by greatestfall** [mBlinkii/mMediaTag#39]
This issue only started happening after I updated to the newest revision.  Basically the top line gets either overwritten by the mana cost or in the case of this stormkeeper talent it just shows nothing on the top line.  Once I disabled the tooltip in nMediaTag the problem went away. 

![ButteryXraytetra](https://user-images.githubusercontent.com/72944318/208278187-31a12240-d67e-4b85-aecd-d67422bb3a4c.png)

**Comment by mBlinkii** [comment]
Hi, thanks for the info in the latest version it should be fixed and as a bonus icons should now also be displayed for macros in the tooltip.
