### ISSUE TITLE
attempt to call method 'mUpdateKick' (a nil value)

### ISSUE THREAD

**Issue by jeremy-hill** [mBlinkii/mMediaTag#49]
BugSack's reporting this new error for 2.95.1:
```
4x ElvUI_mMediaTag/core/init.lua:102: attempt to call method 'mUpdateKick' (a nil value)
[string "@ElvUI_mMediaTag/core/init.lua"]:102: in function `?'
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
...
```

As called in this function:

```
function mMT:ACTIVE_TALENT_GROUP_CHANGED()
	if E.db[mPlugin].mCastbar.enable then
		mMT:mUpdateKick() -- castbar kick/ kick auf cd
	end
```
if it helps, I've attached how that is configured (I don't believe I've changed anything from defaults): 
![image](https://user-images.githubusercontent.com/66854273/229652253-ff8168d4-eb95-4a48-9ead-a482828eb533.png)

**Comment by jeremy-hill** [comment]
Also some change in the most recent patch seemed to have broken my Clique mouseover heal/dispelling.

**Comment by mBlinkii** [comment]
Hi, thx for your feedback, the castbar bug should be fixed with this version https://github.com/mBlinkii/mMediaTag/releases/tag/v.2.95.2.

**Comment by mBlinkii** [comment]
> Also some change in the most recent patch seemed to have broken my Clique mouseover heal/dispelling.

mMediaTag doesn't do anything special with the unit frames, I use Clique myself and haven't noticed any problems with it. could only imagine that there is something invisible over the frames, like a WA that prevents clicking.
