### ISSUE TITLE
Add Venthyr Sinstone to Teleports toys menu

### ISSUE THREAD

**Issue by u8Jj3** [mBlinkii/mMediaTag#72]
Hello, well it would be great to add it... I don't know if there is missing more heartstone but this one is missing atleast :)

Thanks !

**Comment by mBlinkii** [comment]
Yes, will add them. i also need to add the new season teleports. Version 3.23 was just a quick update for ElvUI so the guys can play without bugs, I don't have much time to make progress on mMT at the moment.

**Comment by mBlinkii** [comment]
https://github.com/mBlinkii/mMediaTag/commit/a9b44e8ca3760e5c6e3be6961be80b9e3a4695db

have added it
